Update python 2 to 3 (SOFTWARE-4786)
opensciencegrid/osg-pki-tools pull request #66
Opened 2021-09-03 16:04 UTC by mtru32

2021-09-03 16:27 UTC, DrDaveD requested changes
Thanks for doing this conversion!

The github workflow did not run.  I don't know the details of how to do that, but I assume something needs to be configured by a repo administrator to enable that.  I do not have administrator privileges.  @brianhlin can you enable it?

I noticed that the rpm spec file has not been updated to require python3.  Please test building rpms also in github actions.    [Here is an example](https://github.com/hpcng/singularity/blob/master/.github/workflows/ci.yml#L96) of how to do that.

2021-09-03 16:34 UTC, brianhlin commented
Hi @DrDaveD, @mtru32's one of our students so I'd like to limit this PR to the Python-only changes and the GHA. We'll handle the RPM packaging in a separate PR.

WRT the GHA not running, all the repo settings look good. I think it's because the target branch has to have the workflow already merged in. @mtru32 would you be able to submit a PR for the Python2 GHA branch that you've got?

2021-09-03 17:22 UTC, brianhlin commented
@DrDaveD ok, we had to have the GHA workflow in master before the updates to the workflow would run on this branch. Note that we don't have any tests for `osg-incommon-cert-request`.

2021-09-03 17:26 UTC, DrDaveD approved these changes

2021-09-03 17:28 UTC, DrDaveD commented
Oh yeah there's an issue #53 for writing those unit tests, assigned to @jteheran but she never got around to it.

2021-09-07 16:54 UTC, brianhlin reviewed
Looks mostly good except for a few regex tests being swapped around.

The only other thing I see potentially being an issue is handling encoding where we [write files](https://github.com/opensciencegrid/osg-pki-tools/blob/ddd9706a2ddbb90a0832bd30a472e6e20dcc92ed/osgpkitools/utils.py#L18). One easy way to test this would be to check the contents of the generated CSR in the old version vs your Python 3 version. I'd be happy to merge this in for now and have you test that as part of https://opensciencegrid.atlassian.net/browse/SOFTWARE-4784

2021-09-07 16:54 UTC, brianhlin commented on osgpkitools/cert_utils.py
> +            return getpass.getpass(pass_str+f" '{userkey}':")
```suggestion
            return getpass.getpass(pass_str + f" '{userkey}':")
```

Just a quick whitespace change for my own sanity

2021-09-07 16:54 UTC, brianhlin commented on tests/OSGPKIUtilsTests.py
> +        self.assertIsNone(re.search(r'X509v3 Subject Alternative Name: critical', csr_contents),
This seems to flip the test around. We want to make sure that we find this search string

2021-09-07 16:54 UTC, brianhlin commented on tests/test_cert_request.py
> +                self.assertIsNone(re.search(r'error.*is required.*', stderr.getvalue()))
Another case where I believe this flips the test

2021-09-24 18:48 UTC, brianhlin approved these changes
LGTM!

2021-09-24 18:48 UTC, merged